-- Integration tests (control-stage only, requires game state)
require("tests.integration.register")
require("tests.integration.neighborhood")
require("tests.integration.subentities")
require("tests.integration.inventories")
require("tests.integration.entity-composter")
require("tests.integration.inhabitants-castes")
require("tests.integration.inhabitants-housing")
require("tests.integration.inhabitants-workforce")
require("tests.integration.inhabitants-health")
require("tests.integration.inhabitants-housing-update")
require("tests.integration.inhabitants-homelessness")
