Tirislib.RecipeCategory("sosciencity-handcrafting"):make_hand_craftable()
Tirislib.RecipeCategory("sosciencity-architecture"):make_hand_craftable()
Tirislib.RecipeCategory("sosciencity-fishery-hand"):make_hand_craftable()
Tirislib.RecipeCategory("sosciencity-hunting"):make_hand_craftable()
Tirislib.RecipeCategory("sosciencity-pharma"):make_hand_craftable()
Tirislib.RecipeCategory("sosciencity-plant-upbringing"):make_hand_craftable()
Tirislib.RecipeCategory("sosciencity-slaughter"):pair_with("crafting")
Tirislib.RecipeCategory("sosciencity-wood-processing"):pair_with("crafting")
